= Morality

What is morality?

It is the difference between right and wrong and what governs our decisions.

== Sources

- Bible
- Church
- Conscience
- Example and Teachings of Jesus
- Law

== Reasons Christians Try to Do Good

- It is the "right" thing to do
- God created the world and man 'in imago dei' so we should live and act in a way that is pleasing to him
- God is our judge and we will be judged on how we have acted in life (sheep and goats)
- God will reward up in Heaven
- We should try to be like God, good

== Conscience

The conscience is how we instictively know what is right and wrong.

Christians believe that our conscience comes from God and that is how God speaks to them and that he makes us feel guilty for our sins.

Others would say that it comes from our up bringing and teachers/parents.

== The Bible
Christians study the teachings of the Bible and to try and work out how to apply it to their modern lives.

They believe that the Bible can help them make moral decisions because it is the word of God and they can see what God wants them to do.

Some of the Bible's teachings, such as the *Ten Commandments* can be seen as laws which tell Christians what is right and wrong.

TODO: TEN COMMANDMENTS

However it using the Bible as a source of morality can be an issue as it was written for an older time.

rs::quote[Matthew 7:12, Golden Rule]

== Jesus
*What Would Jesus Do?*

Some Christians take use the actions of Jesus as a guide for wether an action is right or wrong as he was the Son of God and would know.

They would try to copy him; for example the mighty read the Gospels about the ways that Jesus helper out casts and try to apply this to the modern world and help the home less.

They might also look at his attitudes to other topics such as women, war and violence.

rs::quote[Luke 10:27]

== The Church
Christians also look to the Church and its representatives for advice on what is right and wrong.

The Church may issue a formal statement on a subject (e.g. gay marrige)

People would also look towards leaders such as the Pope or their local vicar.
