= Introduction to the Cold War

== Causes

.Different Beliefs
- The USSR was a communist contry; it believed that the state should
  own all the main factories and farms and share the wealth between
  its people.
- The USSR believed the aim of communism was a "world revolution" and
  every country would be communist.
- The USSR were communist and the US were capitalists.

.Suspisions before the end of WW2
- After WW1, the west had taken some land from the USSR and gave it to
  Poland.
- Few people could forget Stalin had signed a treaty with Hitler in
  1939.
- The USSR had lost 11M soldiers and 12M citizens compared to UK/US
  > 1M. Stalin suspected the US had manipulated them to do most of the
  fighting.
- Throughout WW2 the US

.Different ideas for WW2
- The US and UK didn't want to repeat the same mistake as in WW1 and
  treat Germany to harshly, the USSR disagreed and wanted them to pay
  huge reparations to Russia.
- After WW2 the USSR wanted satellite nations between itself and
  Germany that would be communist and controlled by them as they
  thought this would provide them with protection in the case of a
  future war.
- After WW2 the US wanted every country to choose its own system of
  government and leader (including Germany and USSR) (not satilites).

== The Grand Alliance

[qanda]
What was the Grand Alliance?::
  It was an alliance to defeat the Nazis. It was a marriage of
  convenience.

When was it created?::
  1941

What were the 3 unwritten agreements?::
  - The USSR could 'influence' Poland, Czechoslovakia, the Baltic
    States, Hungary and Romania. This would be a 'buffer' between
    the East and West. However they still had to be free and
    democratic.
  - The USSR wanted its influence in communist Yugoslavia.
  - The US and UK wanted the USSR to accept their influence in Western
    Europe, Greece and Italy.
