= Recap Questions

.What is meant by original sin?
The sin that entered the world when Adam and Eve disobeyed God by eating the fruit from the Tree of Knowledge of Good and Evil and that everyone is born with.

.What is meant by the Fall and where in the Bible would you find the story?
The Fall is when man kind lost its state of innocence and its perfect relationship with God by commit the Original Sin and disobeying him.

.Who are the 4 main charters in the story of the Fall?
Adam, Eve, Snake (Devil), God

.Explain where a Christian might look for guidance on the right way to behave.
Jesus, Bible, heart (conscience given by God)

.What is the main theme of the story of Job? What does it teach Christians about suffering?

The story of Job is when God lets the Devil test a man called Job with suffering as a way to test his faith, he remains faithful and God rewards him.

This teaches Christians:
- God always has a plan for you.
- God will not test you more than you can bear.
- That faith will sustain you.
- That suffering is not always our fault.

.What is the type of evil caused by the actions of humans?
Moral Evil

.What is natural evil?
Evil that comes about at no fault of humanity (e.g. hurricane)

.Give two examples of moral/natutal evil. Explain 2 arguments for the existence of suffering?

Natural, hurricane or earthquake. Moral, genocide (Final Solution) or exploiting those less fortunate (loan sharks).

- It is God testing us.
- It is the Devil trying sway us from belief in God.
- It is punishment for our sins.

.Short paragraph on Christian conscience
As a Christian you would have many sources of morality on which you can draw. One of these is the Bible, the Bible though
