== Key Words
[horizontal]
Big Bang:: A scientific theory that a cosmic explosion caused the universe to exist.

creation:: The act of creating something, or the thing that is made, in the Bible, the making of the world by God.

Creationist/Literalists:: A name given to Christians who interpret the Bible literally and accept every word of Genesis as literally true.

Cosmology:: The study of the origins of the universe.

dominion:: The idea that humans have control over or responsibility for the Earth.

evolution:: The way in which animals and plants adapt to their surroundings -- survival of the fittest.

ex nihlio:: A latin term meaning "out of nothing"

Genesis:: The first book of the Bible containing the stories of creation.

humanity:: Caring and showing kindness to others, often a term used for all humans.

Non-literalists:: A name given to a Christian who interprets the Bible as more of a story that literalists and believe it contains important truths but is not a factual account.

stewardship:: The God given right or responsibility to care for the manage the world.
