= Truman Doctrine and The Marshal Plan =
Joshua Coles <josh@coles.to>
$(date)

[horizontal]
Doctrine:: A number of beliefs held by a group.
Isolationism:: The policy of not interfering with foreign affairs.
Containment:: The policy that they would to control and contain the spread of communism.

== Reasons for tensions between US and USSR ==
- Differing ideologies
- Development of the Atomic Bomb
- They supported opposing groups in Greece.
- The USSR wanted heavier reparations for Germany.

== Truman Doctrine ==
Truman discovered that the USSR was in no place to wage a war however they believed Stalin would encourage communist revolutions across Europe to avoid a direct they could not win. This would be much easier for Stalin as most of Europe was left devastated by the war, prime breeding ground for communists ideals.

In response to this Truman set out the Truman Doctrine which said:
  - The world had to choose between tyrannical communism and democratic, free, capitalism.
  - America had a responsibility to fight for freedom wherever it was threatened.
  - America would send troops and economic support to those countries that were threatened by communism.
  - That communism should not be allowed to grow.

This marked the end of American *"isolationism"* and the beginning of the Cold War.

=== Effects on US and USSR Relations ===
The Truman Doctrine lead to increased tensions between the US and USSR as it was the first open criticism of the USSR and communism by the US government (while there had been much negative sentiment this was the first time that it had come to fruition with a public statment). It started a very with us or against us mentality which in which the US pitched the capitalist world against the communist and ended their period of isolationism.

== The Marshal Plan (1947) ==
Described as "half of the walnut of containment"

The Marshal Plan gave $13Bn to help rebuild the shattered economies of Europe. This worked with the military force of America to help contain communism.

The Marshal Plan had two benefits for the US 1) they halted the spread of communism and 2) to receive American money the had to agree to agree to freely trade with America helping the US economy.

The European leaders met at the Paris Conference (1948) to discuss the American offer, the USSR representative walked out of the conference. Stalin insisted the Eastern European countries did not accept the aid.
