= The Breakdown of the Grand Alliance

== Who were the Big Three?
The Big Three were the US (Roosevelt), UK (Churchill) and USSR (Stalin).

== Areas of Disagreement
While all of the Big Three agreed democracy was important they differed in how this should be implemented:

[horizontal]
US:: Believed that democracy was where a number of political parties competing for the peoples support in free elections.

USSR:: They believed that democracy that could only take place in a communist society as it gave the power completely to the people - no free elections.

== Potsdam (1945)
=== Why was it so difficult?
- Both Roosevelt and Churchill had been replaced by Truman and Attlee respectively. This meant they didn't have the same trust as they did previously.
- They no longer had a common enemy were not as united.
- Truman delayed the meeting till after the testing of the atomic bomb, the detonation of which Stalin had not been informed about, this increased his suspicions that Truman was planning to hurt the USSR.

=== Agreements
Germany was divided into 4 sections which had distinctly differing views and governance models.

=== Subjects

.Repairations
- The USSR wanted to impose heavy reparations on Germany where as the US wanted it rebuilt.
- Came to compromise where each party would take reparations from the area it controlled.
* Far less than Stalin wanted as his area was much poorer and had less industry.
* This lead to an agreement where the USSR would trade some of the coal and other resources present in its area for 1/4 of the industry controlled by the West.

.The Atomic Bomb
- Truman attempted to assert authority at the meeting.
* Churchill: "generally bossed the whole meeting".
- Truman believed it was the "master card" due to its destructive power.
- Stalin "showed no special interest" and was not intimidated by the bomb.
* Stalin did however understand its significance and had been trying to make one since 1940.
* Lead to a stronger push on the "buffer zone".

.Poland
- Stalin had agreed to setup an equal government in Poland however this was not the case with it being heavily communist.

.Greece
- The US and UK supported the monarchists.
- The USSR supported the communists.

The Potsdam conference was a source of much debate between the big three especially the US and USSR. Most of this debate and friction was caused by Truman's heavy handedness and over reliance on the atomic bomb in debates which stalin was not happy with or massively affected by. It was not helped however when the governmental conflicts of Poland and Greece once again came up on which the West were directly opposed to the USSR and believed they had broken their word on setting up a fair government in Poland. These two factors would combined together to produce an air of frustration and uncertain at the meeting of the most powerful nations on Earth.
