= The Breakdown of the Grand Alliance

== Who were the Big Three?
The Big Three were the US (Roosevelt), UK (Churchill) and USSR (Stalin).

== Areas of Disagreement
While all of the Big Three agreed democracy was important they differed in how this should be implemented:

[horizontal]
US:: Believed that democracy was where a number of political parties competing for the peoples support in free elections.

USSR:: They believed that democracy that could only take place in a communist society as it gave the power completely to the people - no free elections.

== Potsdam (1945)
=== Why was it so difficult?
- Both Roosevelt and Churchill had been replaced by Truman and Attlee respectively. This meant they didn't have the same trust as they did previously.
- They no longer had a common enemy were not as united.
- Truman delayed the meeting till after the testing of the atomic bomb, the detonation of which Stalin had not been informed about, this increased his suspicions that Truman was planning to hurt the USSR.

=== Agreements
Germany was divided into 4 sections which had distinctly differing views and governance models.
