= Creationism =
Joshua Coles <josh@coles.to>
$(date)

The Genesis accounts of the creation of the world relies on the *existence of God*. This creation is meant to take place over a period of *6 days*. God speaks and the *universe is formed 'ex nihilo'* (from nothing). Everything that was made was described as *good* and *nothing was created by chance*. Everything *had a purpose or a meaning*. Genesis does not mention the Big Bang or evolution which appears to contradict science and evidence.

Some Christians the Genesis account (Adam and Eve / 7 days) *literall* and think that science is mistaken. These Christians do *not* think of the creations story as a *myth* or *symbol* because that would *undermine their beliefs*. These Christians might argue that God's word is clearly stated in the Bible, and should be accepted by *faith*.

The first account of creation shows God making to world in 6 days. The importance of this passage is not how long a day lasted - the Hebrew word 'ayin' simply means a 'period of time'. Nor is it important whether it matches ip to scientific studies about the order of creation, but that it shows that God planned creation and put everything in place, in order. On the 6th day God creates humans beings and places them in the charge of the whole of creation.

In the second account of creation, humans are made before the plants and animals. The passage is, perhaps, more important than it first seems. When God first makes man, the being he creates is neither male nor female  in the Hebrew text. The being does not become 'male' until the woman is created. Therefore neither of the creation stories say that God made men first.

== Genesis - God's Todo list ==
[horizontal]
Day 1:: Create light and name it day, darkness named night.
Day 2:: Separate water and create sky.
Day 3:: Put water in one place to create land, and call the water seas. Land shall produce vegetation.
Day 4:: Lights in the sky for day and night, create sun, stars and moon.
Day 5:: Creates creatures in water and sky - tell them to reproduce.
Day 6:: Create living creatures on land and humans. Humans rule over other creatures.
Day 7:: Have a rest. all created things are good. This day is holy.

== Key Quotes ==
Genesis 1:1:: In the beginning God created the heavens and the earth.

Genesis 2:1:: Thus the heavens and the earth were completed in all their vast array.

Genesis 2:7:: Then the Lord God formed a man[a] from the dust of the ground and breathed into his nostrils the breath of life, and the man became a living being.
